### ISSUE TITLE
Single Rmd for different outputs?

### ISSUE THREAD

**Issue by MavropaliasG** [drdanholmes/Affiliations#1]
Hi, thank you for this. Disheartening that we need to use such intricate methods with Lua etc, to put some simple affiliations in the document.

Is it possible to have a single Rmd for HTML, PDF, and docx output? If we need to have different files for different outputs, then it defeats the purpose of reproducibility.

**Comment by drdanholmes** [comment]
Thanks for the comment. You do not have to use Lua if you do not care about programmatically generated front matter. If you are willing to harcode the titles, authors and abstract then you can just make an Rmd and have PDF, html or docx output. If you want to have journal specific reference formatting you are always going to need pandoc-citeproc and the CSL file of your journal though.
